[env:avatar]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed  = 921600

lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.3
    olikraus/U8g2 @ ^2.35.19
    bblanchon/ArduinoJson @ ^7.3.1
