[env:sentry]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed  = 921600

lib_deps =
    olehs/PZEM-004T-v30 @ ^1.1.2
    madhephaestus/ESP32Encoder @ ^0.11.2
